spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hrms_vhr?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root  # 替换为你的MySQL用户名
    password: 42504  # 替换为你的MySQL密码
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

mybatis:
  type-aliases-package: com.hrms.entity
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080
  servlet:
    session:
      timeout: 1800